# .streamlit/secrets.toml

supabase_url = "https://stzmwkrsdeuuvkddedlv.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0em13a3JzZGV1dXZrZGRlZGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzk4OTgwMjcsImV4cCI6MTk5NTQ3NDAyN30.s88mg7Vl59Dz1KkbKqIU3CHxa95ao7nOIpI9JJxstYs"
